[package]
edition = "2021"
name = "cryptography"
version = "0.1.0"

[dependencies]
jubjub = "0.10.0"
ff = "0.13.1"
group = "0.13.0"
rand = "0.9.2"
sha2 = "0.10"
aes-gcm = "0.10"
generic-array = "1.3.5"
hex = "0.4"
